class WebSocketEvents:
    CONNECTED = "CONNECTED"
    RESOURCE_UPDATED = "RESOURCE_UPDATED"
    ALLOCATION_REQUEST_CREATED = "ALLOCATION_REQUEST_CREATED"
    ALLOCATION_REQUEST_ACCEPTED = "ALLOCATION_REQUEST_ACCEPTED"
    ALLOCATION_REQUEST_REJECTED = "ALLOCATION_REQUEST_REJECTED"
    RESERVATION_CREATED = "RESERVATION_CREATED"
    EMERGENCY_STATUS_UPDATED = "EMERGENCY_STATUS_UPDATED"
    HOSPITAL_STATUS_UPDATED = "HOSPITAL_STATUS_UPDATED"
