"""Add allocation_requests and reservations tables

Revision ID: 011d699aa839
Revises: d15c93812f8f
Create Date: 2026-09-21 15:28:33.763237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011d699aa839'
down_revision: Union[str, Sequence[str], None] = 'd15c93812f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emergency_case_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='allocationrequeststatus_enum', native_enum=False), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['emergency_case_id'], ['emergency_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_requests_emergency_case_id'), 'allocation_requests', ['emergency_case_id'], unique=False)
    op.create_index(op.f('ix_allocation_requests_hospital_id'), 'allocation_requests', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_allocation_requests_id'), 'allocation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_allocation_requests_status'), 'allocation_requests', ['status'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emergency_case_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HELD', 'CONFIRMED', 'RELEASED', 'CONSUMED', 'EXPIRED', name='reservationstatus_enum', native_enum=False), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_reservation_quantity_positive'),
    sa.ForeignKeyConstraint(['emergency_case_id'], ['emergency_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['hospital_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_emergency_case_id'), 'reservations', ['emergency_case_id'], unique=False)
    op.create_index(op.f('ix_reservations_hospital_id'), 'reservations', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_index(op.f('ix_reservations_resource_id'), 'reservations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_resource_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_hospital_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_emergency_case_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_allocation_requests_status'), table_name='allocation_requests')
    op.drop_index(op.f('ix_allocation_requests_id'), table_name='allocation_requests')
    op.drop_index(op.f('ix_allocation_requests_hospital_id'), table_name='allocation_requests')
    op.drop_index(op.f('ix_allocation_requests_emergency_case_id'), table_name='allocation_requests')
    op.drop_table('allocation_requests')
    # ### end Alembic commands ###
