"""add_ambulance_and_handoff_models

Revision ID: 1c38e13ce9fb
Revises: 011d699aa839
Create Date: 2026-09-25 09:37:59.226687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c38e13ce9fb'
down_revision: Union[str, Sequence[str], None] = '011d699aa839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'OFFLINE', name='ambulancestatus_enum', native_enum=False), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    op.create_index(op.f('ix_ambulances_status'), 'ambulances', ['status'], unique=False)
    op.create_index(op.f('ix_ambulances_vehicle_number'), 'ambulances', ['vehicle_number'], unique=True)
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emergency_case_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='handoffstatus_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emergency_case_id'], ['emergency_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoffs_ambulance_id'), 'handoffs', ['ambulance_id'], unique=False)
    op.create_index(op.f('ix_handoffs_emergency_case_id'), 'handoffs', ['emergency_case_id'], unique=False)
    op.create_index(op.f('ix_handoffs_hospital_id'), 'handoffs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_handoffs_id'), 'handoffs', ['id'], unique=False)
    op.create_index(op.f('ix_handoffs_status'), 'handoffs', ['status'], unique=False)
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_ambulance_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_emergency_cases_assigned_ambulance_id'), ['assigned_ambulance_id'], unique=False)
        batch_op.create_foreign_key('fk_emergency_cases_assigned_ambulance_id', 'ambulances', ['assigned_ambulance_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_cases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_emergency_cases_assigned_ambulance_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_emergency_cases_assigned_ambulance_id'))
        batch_op.drop_column('assigned_ambulance_id')
    op.drop_index(op.f('ix_handoffs_status'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_hospital_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_emergency_case_id'), table_name='handoffs')
    op.drop_index(op.f('ix_handoffs_ambulance_id'), table_name='handoffs')
    op.drop_table('handoffs')
    op.drop_index(op.f('ix_ambulances_vehicle_number'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_status'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_table('ambulances')
    # ### end Alembic commands ###
