"""Add emergency case and requirement models

Revision ID: d15c93812f8f
Revises: e821f7897df1
Create Date: 2026-09-20 20:04:45.738387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15c93812f8f'
down_revision: Union[str, Sequence[str], None] = 'e821f7897df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='emergencyseverity_enum', native_enum=False), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('pickup_latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('pickup_longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SEARCHING', 'HOSPITAL_SELECTED', 'EN_ROUTE', 'ARRIVED', 'HANDOFF_COMPLETED', 'CANCELLED', name='emergencystatus_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('pickup_latitude >= -90 AND pickup_latitude <= 90', name='check_pickup_lat_range'),
    sa.CheckConstraint('pickup_longitude >= -180 AND pickup_longitude <= 180', name='check_pickup_lng_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_cases_case_number'), 'emergency_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_emergency_cases_id'), 'emergency_cases', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_cases_severity'), 'emergency_cases', ['severity'], unique=False)
    op.create_index(op.f('ix_emergency_cases_status'), 'emergency_cases', ['status'], unique=False)
    op.create_table('emergency_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emergency_case_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('ICU_BED', 'GENERAL_BED', 'VENTILATOR', 'OXYGEN_BED', 'TRAUMA_BED', 'OPERATING_ROOM', name='resourcetype_enum', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_requirement_quantity_positive'),
    sa.ForeignKeyConstraint(['emergency_case_id'], ['emergency_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_requirements_emergency_case_id'), 'emergency_requirements', ['emergency_case_id'], unique=False)
    op.create_index(op.f('ix_emergency_requirements_id'), 'emergency_requirements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergency_requirements_id'), table_name='emergency_requirements')
    op.drop_index(op.f('ix_emergency_requirements_emergency_case_id'), table_name='emergency_requirements')
    op.drop_table('emergency_requirements')
    op.drop_index(op.f('ix_emergency_cases_status'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_severity'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_id'), table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_case_number'), table_name='emergency_cases')
    op.drop_table('emergency_cases')
    # ### end Alembic commands ###
