"""Initial hospital and resource models

Revision ID: e821f7897df1
Revises: 
Create Date: 2026-09-20 12:31:58.555386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e821f7897df1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('emergency_level', sa.String(length=50), nullable=True),
    sa.Column('trauma_center', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('hospital_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('ICU_BED', 'GENERAL_BED', 'VENTILATOR', 'OXYGEN_BED', 'TRAUMA_BED', 'OPERATING_ROOM', name='resourcetype_enum', native_enum=False), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('available + reserved <= total', name='check_available_plus_reserved_lte_total'),
    sa.CheckConstraint('available >= 0', name='check_available_non_negative'),
    sa.CheckConstraint('reserved >= 0', name='check_reserved_non_negative'),
    sa.CheckConstraint('total >= 0', name='check_total_non_negative'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'resource_type', name='uq_hospital_resource_type')
    )
    op.create_index(op.f('ix_hospital_resources_hospital_id'), 'hospital_resources', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_resources_id'), 'hospital_resources', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_resources_resource_type'), 'hospital_resources', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_resources_resource_type'), table_name='hospital_resources')
    op.drop_index(op.f('ix_hospital_resources_id'), table_name='hospital_resources')
    op.drop_index(op.f('ix_hospital_resources_hospital_id'), table_name='hospital_resources')
    op.drop_table('hospital_resources')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
